server:
  port: 8095

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: yechan
    password: pass
    url: jdbc:postgresql://localhost:5432/divingauth
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        hbm2ddl:
          auto: create
        format_sql: true
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging.level.org.hibernate.SQL: INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE