server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      client-id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key

spring:
  application:
    name: msa-api-gateway

zuul:
  routes:
    msa-user-service:
      path: /api/user/**
    msa-news-service:
      path: /api/news/**
    msa-review-service:
      path: /api/review/**
    msa-advertising-service:
      path: /api/advertising/**
  sensitiveHeaders: Cookie,Set-Cookie